server:
    port: 8080

#数据源
spring:
    profiles:
        active: dev
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    mvc:
      view:
        prefix: /
        suffix: .html
## 默认值为 /**
#      static-path-pattern: /**
## 这里设置要指向的路径，多个使用英文逗号隔开,默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#    resources:
#        static-locations=: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/****/

mybatis:
  #实体类包所在位置
  type-aliases-package: com.ztesoft.springboot_demo.entity
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml

#日志
logging:
    file: log/log.log
    level:
        root: info
        com.ztesoft.springboot_demo: debug
    pattern:
        console: -%clr(%d{yyyy-MM-ddHH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}:%L){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}
        file: -%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } ---[%t] %-40.40logger{39}:%L:%m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}

#配置文件测试
employee:
  name: 沈通
  sex: 男
  age: 24
